### ISSUE TITLE
Write documentation for new TG login system

### ISSUE THREAD

**Issue by mcourtot** [geneontology/termgenie#101]
as per https://github.com/geneontology/termgenie/issues/98

**Comment by mcourtot** [comment]
https://docs.google.com/document/d/1DWgeOy1ICvBAW3xOf18wjGiOK3dg0uOw82Q20mvEbj8/edit

@cmungall, @kltm, @nathandunn: please check/update as needed

@paolaroncaglia, @dosumis, @ukemi, @tberardini: please check this makes sense for users

**Comment by cmungall** [comment]
This is great

Will someone go ahead ad announce? Remember and thank Nathan and Seth - and
help from Heiko

**Comment by paolaroncaglia** [comment]
Thanks @mcourtot , yes the doc makes sense to me. I'm logged into GitHub, so when I tried to log in to TG just now, I was presented with a simpler option, i.e. do I authorise access to my email address rather than a full log in request. But I don't think there's any need to tell users about that option too - if they already are on GitHub, they'll figure it out. Happy for you to announce as you wrote the doc :-)

**Comment by nathandunn** [comment]
@mcourtot  Looks great.   Other than changing the owner (from me), it looks good.

**Comment by tberardini** [comment]
Makes sense to me!

**Comment by ukemi** [comment]
I made one tiny edit, but it makes sense to me too.

**Comment by kltm** [comment]
Okay, I'm making a lot of edits, and it's going too well. I don't think this will work real well as a google doc as there is too much structured into (and it's nearly impossible to get YAML to layout right).

**Comment by kltm** [comment]
Great document though. Would anybody mind if I tried to make this a little more permanent and added this to the go-site repo as a markdown doc, similar to what we have for the Noctua quickstart guide?

**Comment by kltm** [comment]
And maybe generalize it a bit to include Noctua, as they are essentially the same in this aspect.
As well, this would be a chance to push for people to get ORCIDs. Some kind of _uri_ is required anyways.
Do people think a merged doc works for this?
https://github.com/geneontology/go-site/blob/master/documentation/application-logins.md
(I'm not happy how it lays out in go-site like that, but I can't think of a better place to leave it for now...)

**Comment by mcourtot** [comment]
That's amazing, thanks for all the updates @kltm !

I used this to send an email to go-discuss announcing the changes, and am now closing this ticket.
