### ISSUE TITLE
not receiving TG submission emails

### ISSUE THREAD

**Issue by mah11** [geneontology/termgenie#107]
The last two times I did TermGenie submissions (afternoon of Monday 12th, and just now, Thursday 15th Dec.), I didn't receive the usual confirmation email. I also see that the term from Monday (GO:1905755) is available, but I didn't get a "your terms have been committed" email either.

These are the first two times I've used TG since the switch to GitHub logins, although I can't tell whether it's connected or a coincidence (in all other respects GitHub login is actually working better for me than Persona did).

Do I have to configure something?

**Comment by cmungall** [comment]
Apologies for this. See email to go-discuss. Would you be able to live with this for a few months?

When we switch to github we can `@` mention submitters when their terms are committed.

**Comment by mah11** [comment]
Not a problem - the emails were convenient rather than essential, and my own main use case for them was as a backup in case I forgot to copy the IDs from the TG result page. I opened this ticket mainly to make sure the lack of email was expected, and not a symptom of something having gone awry.
