### ISSUE TITLE
Add ability to clone rows

### ISSUE THREAD

**Issue by hdietze** [geneontology/termgenie#44]
Original [issue 44](https://code.google.com/p/termgenie/issues/detail?id=44) created by hdietze on 2014-06-25T21:23:49.000Z:

Sometimes we may have to enter an M x N cross product. E.g.

{neuron,glial cell} and part_of some {forebrain,hindbrain,midbrain}

Here it would be convenient to enter 3 rows

 * forebrain neuron
 * hindbrain neuron
 * midbrain neuron

And then to duplicate these (en masse or one at a time) and replace neuron with glial cell

**Comment by cmungall** [comment]
Won't fix
