### ISSUE TITLE
Duplicate synonym creation

### ISSUE THREAD

**Issue by tberardini** [geneontology/termgenie#69]
Doug Howe reported by email:

It seems there are still a few more instances of duplicate synonyms.  I'm not sure if these are new, or if they just didn't show in the report I had earlier this week.  In Amigo2 the first example below looks like it may have a couple of synonyms duplicated or even triplicated.  Almost seems like a software problem?
Doug

More dups in the file.

(count(*))  2
id          GO:1904171
name        downregulation of bleb assembly
syn        synonym

(count(*))  2
id          GO:1904171
name        down-regulation of bleb assembly
syn        synonym

(count(*))  2
id          GO:1904172
name        up regulation of bleb assembly
syn        synonym

(count(*))  2
id          GO:1904171
name        down regulation of bleb assembly
syn        synonym

(count(*))  2
id          GO:1904172
name        up-regulation of bleb assembly
syn        synonym

(count(*))  2
id          GO:1904172
name        upregulation of bleb assembly
syn        synonym

**Comment by tberardini** [comment]
I'll remove the duplicates manually.  Please investigate cause.

**Comment by tberardini** [comment]
Duplicates removed.

**Comment by cmungall** [comment]
Also downstream check: https://sourceforge.net/p/geneontology/ontology-requests/11658/

**Comment by hdietze** [comment]
The TermGenie code has now a check in the synonym generation which prevents the generation of duplicate synonyms for a single class.

**Comment by hdietze** [comment]
Code is deployed
