### ISSUE TITLE
TermGenieManagement should show version of owlapi

### ISSUE THREAD

**Issue by cmungall** [geneontology/termgenie#72]
This would be v useful for the purposes of coordinating versions of Protege to be used by editors in order to minimize diffs

**Comment by cmungall** [comment]
Edited ticket: originally thought this should be in the management form. But it would be useful for this to be accessed by users without mgmt permissions

**Comment by hdietze** [comment]
The first example is here: http://go.termgenie.org/TermGenieInfo.html

What else should be on the info page?

**Comment by cmungall** [comment]
TermGenie version number (similar to what you did for the owlapi "rest services"). Also if easy, things like reasoner configuration and reasoner version

**Comment by hdietze** [comment]
Update the example to also include:
 * reasonerName
 * reasonerVersion
 * termgenieBuildTimestamp
 * termgenieRevision
 * termgenieRevisionUrl

**Comment by hdietze** [comment]
All the termgenie instances have been re-deployed and with the info page.
