### ISSUE TITLE
Switch MP TG to GH

### ISSUE THREAD

**Issue by cmungall** [geneontology/termgenie#75]
https://github.com/obophenotype/mammalian-phenotype-ontology

pending approval by @cindyJax.

You may want to hold out til we do HP later, this ticket is to ensure we don't forget

**Comment by hdietze** [comment]
The latest possible date is August 23rd 2015, after that google code turns readonly.

**Comment by cindyJax** [comment]
The repo looks good and seems to be working as expected, so whenever you are ready to convert, please go ahead. I would like to start using this more frequently and train a few select users to submit terms through this as well.  Thanks!
