### ISSUE TITLE
NTR new child under Protein Complexes

### ISSUE THREAD

**Issue by pfey03** [geneontology/termgenie#84]
I’m trying to add a new protein binding term in termgenie. Either
‘glycoprotein complex’, which I do not see how to add. Or I tried ‘by
activity’ and added the MF ‘cellulose binding’ for 'cellulose binding protein complex ' as the complex binds
that, but since it’s not an activity GO term I can’t do that. 

I think ‘glycoprotein complex’ would be the term I want to add, a simple child of GO:0043234 protein
complex and parent of the specific glycoprotein terms (such as  GO:0016010 dystrophin-associated glycoprotein complex). This is such a simple new term, would be strange not to use termgenie for that.

A: protein_complex_by_citation
This would allow adding this simple term and the reference(s) describing the complex should be enough. 

B:  protein_complex_by_protein_binding
Could ask for UniProt IDs of the complex partners, but this would probably go too far for Termgenie

PMIDs 7693675, 8662961
I added the following comment when trying termgenie: An example is the
Dictyostelium multi protein pspB complex, which is secreted from
prespore vesicles and incorporated into the spore coat.

**Comment by tberardini** [comment]
Are you trying to request a new TG template for specific complex terms?  I've copied this request over to the main GO term tracker for your particular term.

https://github.com/geneontology/go-ontology/issues/12201
