### ISSUE TITLE
URGENT: Please modify template cell_apoptotic_process

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/termgenie#88]
Stemming from decision of obsoleting 'cell-type specific apoptotic process'
https://github.com/geneontology/go-ontology/issues/12338

Could you please modify the TG template for cell_apoptotic_process as soon as possible, so that the process is GO:0006915 'apoptotic process' instead of the current 'cell-type specific apoptotic process'. Apologies for the inconvenience.

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@hdietze @cmungall

**Comment by hdietze** [comment]
The pattern has been updated and the change has been deployed.

**Comment by paolaroncaglia** [comment]
Tested, all looks ok, many thanks Heiko!
