### ISSUE TITLE
Label check finding submitted freeform term itself

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/termgenie#92]
TermGenie gave me this error when I tried to submit a freeform term today:

Submitted for Review
The commit of the generated terms did not complete normally with the following reason:
Could not commit, a term with the same label already exists: GO:TEMP-0 virus terminase, small subunit 

Heiko said "that is definitely a TG bug. It seems the label check is finding the submitted free form term itself. Seems the check to avoid that has broken during the switch."

**Comment by paolaroncaglia** [comment]
Val was also having trouble, see link above.

**Comment by paolaroncaglia** [comment]
Stan also reported this. @hdietze , it may be worth sending an email to go-consortium as soon as this bug is fixed, so curators can re-submit their terms. Thanks!

**Comment by hdietze** [comment]
Hello,
I have deployed an updated TermGenie version. In tests it seems to be working again. Please verify that it works again for your use-case and the linked requests.

**Comment by hdietze** [comment]
Works for the related tickets.
